name: bebas
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  google_fonts: 6.1.0
  flutter_otp_text_field: ^1.1.3+2
  dio: ^5.4.3+1
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  auto_size_text: ^3.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/app/data/json/allAgenda.json
    - assets/images/Logo1.png
    - assets/images/review.png
    - assets/images/approve.png
